name: iOS CI

on:
  push:
    branches:
      - main

env:
  XCODE_PROJECT: HackerEvent.xcodeproj
  XCODE_SCHEME: HackerEvent

jobs:
  test:
    uses: sersoft-gmbh/xcodebuild-action@v2
    with:
    project: MyApp.xcodeproj
    scheme: MyApp
    destination: platform=macOS
    action: test
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

